<?php

namespace SM\Bundle\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BranchController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SM\Bundle\AdminBundle\Controller\BranchController();
        return $instance;
    }
}
