parameters:
#    sm_admin.example.class: SM\Bundle\AdminBundle\Example

services:
    sm.admin.pool:
        class: SM\Bundle\AdminBundle\Admin\Pool
        arguments:
            - "@service_container"
            - ~
            - ~
    sm_admin.tree.listener:
        class: SM\Bundle\AdminBundle\EventListener\TreeListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }
            
    sm.twig.showimg_extension:
        class: SM\Bundle\AdminBundle\Twig\MTxTwigShowImageExtension
        tags:
            - { name: twig.extension }

    sm.twig.media_extension:
        class: SM\Bundle\AdminBundle\Twig\SMTwigMediaExtension
        tags:
            - { name: twig.extension }