parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: local.tyhv
    database_user: root
    database_password: admin
    host : http://local.tyhv
    locale: vi
    secret: d00245c7bda39aa016baa57370bfebc9b11deda3
    database_path: null

    per_item_page: 10
    upload : "/uploads/"

    menu_type_company_category: 1
    menu_type_company_detail: 2
    menu_type_product_branch: 3
    menu_type_product_group: 4
    menu_type_product_detail: 5
    menu_type_news_category: 6
    menu_type_news_detail: 7
    menu_type_page_detail: 8
