sm_admin:
    dashboard:
        - { class: SM\Bundle\AdminBundle\Entity\User,   group: System, label: User,   acl: true,  action: [admin_user_new, admin_user] }
        - { class: SM\Bundle\AdminBundle\Entity\Language,   group: System, label: Language,   acl: true,  action: [admin_language_new, admin_language] }
        
        - { class: SM\Bundle\AdminBundle\Entity\Branch,   group: Group, label: Branch,   acl: true,  action: [admin_branch_new, admin_branch] }
        - { class: SM\Bundle\AdminBundle\Entity\Group,   group: Group, label: Product Group,   acl: true,  action: [admin_productgroup_new, admin_productgroup] }
        
        - { class: SM\Bundle\AdminBundle\Entity\CompanyType,   group: Company, label: Company Type,   acl: true,  action: [admin_companytype_new, admin_companytype] }
        - { class: SM\Bundle\AdminBundle\Entity\Company,   group: Company, label: Company,   acl: true,  action: [admin_company_new, admin_company] }

    templates: 5