<?php

namespace SM\Bundle\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupsLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsLanguageRepository extends EntityRepository
{
}
