<?php

namespace SM\Bundle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\UnitOfWork;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
    /**
     * Delete language by array id
     *
     * @param array $ids
     *
     * @return array
     */
    public function deleteByIds($ids = array())
    {
        $em = $this->getEntityManager();
        $rst = array();
        if (is_array($ids) && count($ids)) {
            foreach ($ids as $id) {
                $entity = $this->find($id);
                $em->remove($entity);
                if ($em->getUnitOfWork()->getEntityState($entity) == UnitOfWork::STATE_REMOVED) {
                    $rst[] = $id;
                }
            }
            $em->flush();
        }

        return $rst;
    }
    
    /**
     * Find visitor by name
     */
    public function findByName($name)
    {
        $rst = null;
        if (!empty($name)) {
            $rst = $this->findBy(array('name' => $name));
            if (!empty($rst[0])) {
                
                return $rst[0];
            }
        }
        
        return $rst;
    }
    
    /**
     * 
     */
    public function updateByVisitor()
    {
        $obj = $this->findByName('number_visitor');
        $value = $obj->getValue();
        $value ++;
        $obj->setValue($value);
        $em = $this->getEntityManager();
        $em->persist($obj);
        $em->flush();
        
    }
}
