<?php

namespace SM\Bundle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\UnitOfWork;

/**
 * GroupsLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageLanguageRepository extends EntityRepository {

    /**
     * @param type $criteria criteria
     *
     * @return type
     */
    public function getTotal($criteria = array()) {
        $rst = $this->findBy($criteria);

        return count($rst);
    }

    /**
     * @param type $productId productId
     *
     * @return type
     */
    public function findByPageId($id) {
        $rst = array();
        if (!empty($id)) {
            $rst = $this->findBy(array('page' => $id));
        }

        return $rst;
    }

    /**
     * Delete language by array id
     *
     * @param array $ids
     *
     * @return array
     */
    public function deleteByIds($ids = array()) {
        $em = $this->getEntityManager();
        $rep = $em->getRepository('SMAdminBundle:Page');
        
        $rst = array();
        if (is_array($ids) && count($ids)) {
            foreach ($ids as $id) {
                $entity = $this->find($id);
                $id = $entity->getPage()->getId();

                $em->remove($entity);

                //Get all product language by idComtype
                //If to have 1 item we need to delete product too
                //else we need delete product language
                $lstNewsLangs = $this->findByPageId($id);
                if (count($lstNewsLangs) == 1) {
                    if ($em->getUnitOfWork()->getEntityState($entity) == UnitOfWork::STATE_REMOVED) {
                        $rst[] = $id;
                    }
                    $em->persist($entity);
                    //delete product too
                    $em->flush();
                    //delete product language
                    $rep->deleteByIds(array($id));
                } else {
                    if ($em->getUnitOfWork()->getEntityState($entity) == UnitOfWork::STATE_REMOVED) {
                        $rst[] = $id;
                    }
                    //Onlye delete article language
                    $em->flush();
                }
            }
        }

        return $rst;
    }

    /**
     * Find product by condition
     *
     * @param type $langId
     * @param type $name
     * @param type $branchId
     * @param type $productGroupId
     * @return array
     */
    public function findByLangAndName($langId, $name = '', $limit = null, $offset = null)
    {
        $rst = array();
        if (!empty($langId)) {
            $qb = $this->createQueryBuilder('pl');

            $qb->select('pl, p')
                    ->join('pl.page', 'p')
                    ->where('pl.language=:langId');

            if (!empty($limit)) {
                $qb->setMaxResults($limit);
            }

            if (!empty($offset)) {
                $qb->setFirstResult($offset);
            }

            if (!empty($name)) {
                $qb->andWhere('nl.name LIKE ?1');
                $qb->andWhere('nl.intro LIKE ?2');
                $qb->andWhere('nl.description LIKE ?3');
                $qb->setParameter(1, "%$name%");
                $qb->setParameter(2, "%$name%");
                $qb->setParameter(3, "%$name%");
            }

            $qb->setParameter('langId', $langId);
            //echo $qb->getQuery()->getSQL();die;
            return $qb->getQuery()->getResult();
        }

        return $rst;
    }

    /**
     * get total
     *
     * @param type $langId
     * @param type $name
     * @param type $typeId
     * @return int
     */
    public function getTotalByLangAndName($langId, $name = '')
    {
        if (!empty($langId)) {
            $qb = $this->createQueryBuilder('pl');

            $qb->select('pl, p')
                    ->join('pl.page', 'p')
                    ->where('pl.language=:langId');

            if (!empty($limit)) {
                $qb->setMaxResults($limit);
            }

            if (!empty($offset)) {
                $qb->setFirstResult($offset);
            }

            if (!empty($name)) {
                $qb->andWhere('nl.name LIKE ?1');
                $qb->andWhere('nl.intro LIKE ?2');
                $qb->andWhere('nl.description LIKE ?3');
                $qb->setParameter(1, "%$name%");
                $qb->setParameter(2, "%$name%");
                $qb->setParameter(3, "%$name%");
            }

            $qb->setParameter('langId', $langId);

            return count($qb->getQuery()->getResult());
        }
        return 0;
    }

}
