<?php

namespace SM\Bundle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\UnitOfWork;

/**
 * ProductLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLanguageRepository extends EntityRepository
{
    /**
     * @param type $criteria criteria
     *
     * @return type
     */
    public function getTotal($criteria = array()) {
        $rst = $this->findBy($criteria);

        return count($rst);
    }

    /**
     * @param type $productId productId
     *
     * @return type
     */
    public function findByProductId($productId) {
        $rst = array();
        if (!empty($productId)) {
            $rst = $this->findBy(array('product' => $productId));
        }

        return $rst;
    }

    /**
     * Delete language by array id
     *
     * @param array $ids
     *
     * @return array
     */
    public function deleteByIds($ids = array()) {
        $em = $this->getEntityManager();
        $repProducts = $em->getRepository('SMAdminBundle:Products');

        $rst = array();
        if (is_array($ids) && count($ids)) {
            foreach ($ids as $id) {
                $entity = $this->find($id);
                $idProduct = $entity->getProduct()->getId();

                $em->remove($entity);

                //Get all product language by idComtype
                //If to have 1 item we need to delete product too
                //else we need delete product language
                $lstProductLangs = $this->findByProductId($idProduct);
                if (count($lstProductLangs) == 1) {
                    if ($em->getUnitOfWork()->getEntityState($entity) == UnitOfWork::STATE_REMOVED) {
                        $rst[] = $id;
                    }
                    $em->persist($entity);
                    //delete product too
                    $em->flush();
                    //delete product language
                    $repProducts->deleteByIds(array($idProduct));
                } else {
                    if ($em->getUnitOfWork()->getEntityState($entity) == UnitOfWork::STATE_REMOVED) {
                        $rst[] = $id;
                    }
                    //Onlye delete article language
                    $em->flush();
                }
            }
        }

        return $rst;
    }

    /**
     * Find product by condition
     *
     * @param type $langId
     * @param type $name
     * @param type $branchId
     * @return array
     */
    public function findByLangAndNameAndBranchAndProductGroup($langId, $name = '', $branchId = '', $limit = null, $offset = null)
    {
        $rst = array();
        if (!empty($langId)) {
            $qb = $this->createQueryBuilder('pl');

            $qb->select('pl, p')
                    ->join('pl.product', 'p')
                    ->join('p.branch', 'b')
                    ->where('pl.language=:langId');

            if (!empty($limit)) {
                $qb->setMaxResults($limit);
            }

            if (!empty($offset)) {
                $qb->setFirstResult($offset);
            }

            if (!empty($branchId)) {
                $qb->andWhere('p.branch=:branchId');
                $qb->setParameter('branchId', $branchId);
            }

            if (!empty($name)) {
                $qb->andWhere('pl.name LIKE ?1');
                $qb->setParameter(1, "%$name%");
            }

            $qb->setParameter('langId', $langId);
            //echo $qb->getQuery()->getSQL();die;
            return $qb->getQuery()->getResult();
        }

        return $rst;
    }

    /**
     * get total
     *
     * @param type $langId
     * @param type $name
     * @param type $typeId
     * @return int
     */
    public function getTotalByLangAndNameAndType($langId, $name = '', $branchId = '')
    {
        if (!empty($langId)) {
            $qb = $this->createQueryBuilder('pl');

            $qb->select('pl, p')
                    ->join('pl.product', 'p')
                    ->join('p.branch', 'b')
                    ->where('pl.language=:langId');

            if (!empty($branchId)) {
                $qb->andWhere('p.branch=:branchId');
                $qb->setParameter('branchId', $branchId);
            }

            if (!empty($name)) {
                $qb->andWhere('pl.name LIKE ?1');
                $qb->setParameter(1, "%$name%");
            }

            $qb->setParameter('langId', $langId);

            return count($qb->getQuery()->getResult());
        }
        return 0;
    }
}
