<?php

namespace Proxies\__CG__\SM\Bundle\AdminBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Products extends \SM\Bundle\AdminBundle\Entity\Products implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPrice($price)
    {
        $this->__load();
        return parent::setPrice($price);
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function setUnit($unit)
    {
        $this->__load();
        return parent::setUnit($unit);
    }

    public function getUnit()
    {
        $this->__load();
        return parent::getUnit();
    }

    public function setDiscount($discount)
    {
        $this->__load();
        return parent::setDiscount($discount);
    }

    public function getDiscount()
    {
        $this->__load();
        return parent::getDiscount();
    }

    public function setThumb($thumb)
    {
        $this->__load();
        return parent::setThumb($thumb);
    }

    public function getThumb()
    {
        $this->__load();
        return parent::getThumb();
    }

    public function setAmount($amount)
    {
        $this->__load();
        return parent::setAmount($amount);
    }

    public function getAmount()
    {
        $this->__load();
        return parent::getAmount();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setCreated(\SM\Bundle\AdminBundle\Entity\User $created = NULL)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setUpdated(\SM\Bundle\AdminBundle\Entity\User $updated = NULL)
    {
        $this->__load();
        return parent::setUpdated($updated);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function addProductLanguage(\SM\Bundle\AdminBundle\Entity\ProductLanguage $productLanguages)
    {
        $this->__load();
        return parent::addProductLanguage($productLanguages);
    }

    public function removeProductLanguage(\SM\Bundle\AdminBundle\Entity\ProductLanguage $productLanguages)
    {
        $this->__load();
        return parent::removeProductLanguage($productLanguages);
    }

    public function getProductLanguages()
    {
        $this->__load();
        return parent::getProductLanguages();
    }

    public function setBranch(\SM\Bundle\AdminBundle\Entity\Branch $branch = NULL)
    {
        $this->__load();
        return parent::setBranch($branch);
    }

    public function getBranch()
    {
        $this->__load();
        return parent::getBranch();
    }

    public function setCreatedAtValue()
    {
        $this->__load();
        return parent::setCreatedAtValue();
    }

    public function setLanguage(\SM\Bundle\AdminBundle\Entity\Language $language)
    {
        $this->__load();
        return parent::setLanguage($language);
    }

    public function getLanguage()
    {
        $this->__load();
        return parent::getLanguage();
    }

    public function getCurrentLanguage()
    {
        $this->__load();
        return parent::getCurrentLanguage();
    }

    public function hasLanguage(\SM\Bundle\AdminBundle\Entity\Language $language)
    {
        $this->__load();
        return parent::hasLanguage($language);
    }

    public function addMediaId(\SM\Bundle\AdminBundle\Entity\Media $mediaId)
    {
        $this->__load();
        return parent::addMediaId($mediaId);
    }

    public function removeMediaId(\SM\Bundle\AdminBundle\Entity\Media $mediaId)
    {
        $this->__load();
        return parent::removeMediaId($mediaId);
    }

    public function getMediaId()
    {
        $this->__load();
        return parent::getMediaId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'price', 'unit', 'discount', 'thumb', 'amount', 'status', 'created_at', 'updated_at', 'created', 'updated', 'product_languages', 'branch', 'media_id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}